import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:intl/intl.dart';
import 'package:planerz/features/ingredients/data/ingredient_catalog_item.dart';
import 'package:planerz/features/ingredients/data/ingredient_catalog_repository.dart';
import 'package:planerz/features/meals/data/meal_component_risks.dart';
import 'package:planerz/features/meals/data/meals_repository.dart';
import 'package:planerz/features/meals/data/trip_meal.dart';
import 'package:planerz/features/meals/presentation/meal_component_editor_page.dart';
import 'package:planerz/features/trips/data/trip_day_part.dart';
import 'package:planerz/features/trips/data/trip_member_stay.dart';
import 'package:planerz/features/trips/data/trips_repository.dart';
import 'package:planerz/l10n/app_localizations.dart';

class TripMealDetailsPage extends ConsumerStatefulWidget {
  const TripMealDetailsPage({
    super.key,
    required this.tripId,
    this.mealId,
  });

  final String tripId;
  final String? mealId;

  bool get isCreate => mealId == null || mealId!.trim().isEmpty;

  @override
  ConsumerState<TripMealDetailsPage> createState() =>
      _TripMealDetailsPageState();
}

class _TripMealDetailsPageState extends ConsumerState<TripMealDetailsPage> {
  final _formKey = GlobalKey<FormState>();
  late final TextEditingController _nameController;
  bool _isSaving = false;
  bool _isDeleting = false;
  bool _isHydrated = false;
  DateTime _mealDate = DateUtils.dateOnly(DateTime.now());
  TripDayPart _mealDayPart = TripDayPart.midday;
  Set<String> _participantIds = <String>{};
  String? _chefParticipantId;
  String _lastAutoGeneratedName = '';
  List<MealComponent> _components = const [];
  String? _initialMealSignature;
  Map<String, String> _initialComponentSignatures = const {};
  bool _allowNextPop = false;

  @override
  void initState() {
    super.initState();
    _nameController = TextEditingController();
  }

  @override
  void dispose() {
    _nameController.dispose();
    super.dispose();
  }

  String get _mealDateKey => TripMemberStay.dateKeyFromDateTime(_mealDate);

  String _defaultMealName() {
    final l10n = AppLocalizations.of(context)!;
    final moment = _mealMomentLabel(l10n, _mealDayPart);
    final localeTag = Localizations.localeOf(context).toString();
    final dayName = DateFormat('EEEE', localeTag).format(_mealDate);
    final dateLabel = DateFormat('d MMMM', localeTag).format(_mealDate);
    return '$moment $dayName $dateLabel';
  }

  String _mealMomentLabel(AppLocalizations l10n, TripDayPart dayPart) {
    return switch (dayPart) {
      TripDayPart.morning => l10n.mealMomentBreakfast,
      TripDayPart.midday => l10n.mealMomentLunch,
      TripDayPart.evening => l10n.mealMomentDinner,
    };
  }

  String _componentKindLabel(AppLocalizations l10n, MealComponentKind kind) {
    return switch (kind) {
      MealComponentKind.entree => l10n.mealComponentKindEntree,
      MealComponentKind.plat => l10n.mealComponentKindMain,
      MealComponentKind.dessert => l10n.mealComponentKindDessert,
      MealComponentKind.autre => l10n.mealComponentKindOther,
    };
  }

  void _refreshAutoNameIfNeeded() {
    if (!widget.isCreate) return;
    final current = _nameController.text.trim();
    final nextAutoName = _defaultMealName();
    final canReplace = current.isEmpty || current == _lastAutoGeneratedName;
    if (!canReplace) return;
    _nameController.text = nextAutoName;
    _lastAutoGeneratedName = nextAutoName;
  }

  void _hydrateFromMeal(TripMeal meal) {
    if (_isHydrated) return;
    _nameController.text = meal.name;
    _mealDate = meal.mealDateAsDateTime;
    _mealDayPart = meal.mealDayPart;
    _participantIds = meal.participantIds.toSet();
    _chefParticipantId = meal.chefParticipantId != null &&
            _participantIds.contains(meal.chefParticipantId)
        ? meal.chefParticipantId
        : null;
    _components = meal.components.toList(growable: true)
      ..sort((a, b) => a.order.compareTo(b.order));
    _saveCurrentAsBaseline();
    _isHydrated = true;
  }

  String _componentSignature(MealComponent component) {
    final ingredients = component.ingredients
        .map(
          (ingredient) =>
              '${ingredient.catalogItemId.trim()}|${ingredient.label.trim()}|'
              '${ingredient.quantityValue}|${ingredient.quantityUnit.trim()}',
        )
        .join('~');
    return '${component.order}|${component.kind.firestoreValue}|'
        '${component.title.trim()}|$ingredients';
  }

  Map<String, String> _componentSignaturesById(List<MealComponent> components) {
    return {
      for (final component in components)
        component.id: _componentSignature(component),
    };
  }

  String _currentMealSignature() {
    final sortedParticipants = _participantIds.toList()..sort();
    final componentsSignature = _components
        .map((component) => '${component.id}:${_componentSignature(component)}')
        .join('||');
    return '${_nameController.text.trim()}|$_mealDateKey|'
        '${tripDayPartToFirestore(_mealDayPart)}|'
        '${sortedParticipants.join(",")}|${_chefParticipantId ?? ""}|'
        '$componentsSignature';
  }

  void _saveCurrentAsBaseline() {
    _initialMealSignature = _currentMealSignature();
    _initialComponentSignatures = _componentSignaturesById(_components);
  }

  bool get _hasUnsavedChanges {
    final baseline = _initialMealSignature;
    if (baseline == null) return false;
    return baseline != _currentMealSignature();
  }

  Set<String> get _changedComponentIds {
    final current = _componentSignaturesById(_components);
    final changed = <String>{};
    for (final entry in current.entries) {
      if (_initialComponentSignatures[entry.key] != entry.value) {
        changed.add(entry.key);
      }
    }
    for (final initialId in _initialComponentSignatures.keys) {
      if (!current.containsKey(initialId)) {
        changed.add(initialId);
      }
    }
    return changed;
  }

  Future<bool> _confirmDiscardIfNeeded() async {
    if (!_hasUnsavedChanges) return true;
    final confirm = await showDialog<bool>(
      context: context,
      builder: (dialogContext) => AlertDialog(
        title: Text(AppLocalizations.of(context)!.commonUnsavedChangesTitle),
        content: Text(
          AppLocalizations.of(context)!.mealUnsavedChangesBody,
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(dialogContext).pop(false),
            child: Text(AppLocalizations.of(context)!.commonStay),
          ),
          FilledButton(
            onPressed: () => Navigator.of(dialogContext).pop(true),
            child: Text(AppLocalizations.of(context)!.tripOverviewLeaveAction),
          ),
        ],
      ),
    );
    return confirm == true;
  }

  void _addComponent(MealComponentKind kind) {
    setState(() {
      _components = [
        ..._components,
        MealComponent(
          id: 'cmp_${DateTime.now().microsecondsSinceEpoch}_${_components.length}',
          kind: kind,
          order: _components.length,
          ingredients: const [],
        ),
      ];
    });
  }

  Future<void> _openComponentEditor({
    required MealComponent component,
    required List<IngredientCatalogItem> catalogItems,
    required Set<String> participantAllergenIds,
  }) async {
    final updated = await Navigator.of(context).push<MealComponent>(
      MaterialPageRoute(
        builder: (_) => MealComponentEditorPage(
          component: component,
          catalogItems: catalogItems,
          participantAllergenIds: participantAllergenIds,
        ),
      ),
    );
    if (!mounted || updated == null) return;
    _updateComponent(updated.copyWith(order: component.order));
  }

  void _updateComponent(MealComponent next) {
    setState(() {
      _components = _components
          .map((component) => component.id == next.id ? next : component)
          .toList(growable: false);
    });
  }

  void _deleteComponent(String componentId) {
    setState(() {
      final filtered = _components
          .where((component) => component.id != componentId)
          .toList(growable: false);
      _components = [
        for (var i = 0; i < filtered.length; i++)
          filtered[i].copyWith(order: i),
      ];
    });
  }

  void _reorderComponents(int oldIndex, int newIndex) {
    setState(() {
      final next = _components.toList(growable: true);
      if (newIndex > oldIndex) {
        newIndex -= 1;
      }
      final moved = next.removeAt(oldIndex);
      next.insert(newIndex, moved);
      _components = [
        for (var i = 0; i < next.length; i++) next[i].copyWith(order: i),
      ];
    });
  }

  Future<void> _autoRecalculateParticipants(List<String> memberIds) async {
    try {
      final ids =
          await ref.read(mealsRepositoryProvider).calculateMealParticipants(
                tripId: widget.tripId,
                mealDateKey: _mealDateKey,
                mealDayPart: tripDayPartToFirestore(_mealDayPart),
                allMemberIds: memberIds,
              );
      if (!mounted) return;
      setState(() {
        _participantIds = ids.toSet();
        if (_chefParticipantId != null &&
            !_participantIds.contains(_chefParticipantId)) {
          _chefParticipantId = null;
        }
      });
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context)
          .showSnackBar(
            SnackBar(
              content: Text(
                AppLocalizations.of(context)!.commonErrorWithDetails(
                  e.toString(),
                ),
              ),
            ),
          );
    }
  }

  void _selectAllParticipants(List<String> memberIds) {
    setState(() {
      _participantIds = memberIds.toSet();
      if (_chefParticipantId != null &&
          !_participantIds.contains(_chefParticipantId)) {
        _chefParticipantId = null;
      }
    });
  }

  void _toggleChefParticipant(String participantId) {
    if (!_participantIds.contains(participantId)) return;
    setState(() {
      if (_chefParticipantId == participantId) {
        _chefParticipantId = null;
      } else {
        _chefParticipantId = participantId;
      }
    });
  }

  Future<void> _pickDate() async {
    final picked = await showDatePicker(
      context: context,
      locale: Localizations.localeOf(context),
      initialDate: _mealDate,
      firstDate: DateTime(2000),
      lastDate: DateTime(2100),
      helpText: AppLocalizations.of(context)!.mealDateHelp,
    );
    if (picked == null || !mounted) return;
    setState(() {
      _mealDate = DateUtils.dateOnly(picked);
      _refreshAutoNameIfNeeded();
    });
  }

  Future<void> _save() async {
    if (_isSaving) return;
    final form = _formKey.currentState;
    if (form == null || !form.validate()) return;

    setState(() => _isSaving = true);
    try {
      final repo = ref.read(mealsRepositoryProvider);
      final mealDayPart = tripDayPartToFirestore(_mealDayPart);
      final participantIds = _participantIds.toList()..sort();
      if (widget.isCreate) {
        await repo.addMeal(
          tripId: widget.tripId,
          name: _nameController.text,
          mealDateKey: _mealDateKey,
          mealDayPart: mealDayPart,
          participantIds: participantIds,
          chefParticipantId: _chefParticipantId,
          notes: '',
          components: _components,
        );
        if (!mounted) return;
        Navigator.of(context).pop();
        ScaffoldMessenger.of(context)
            .showSnackBar(
              SnackBar(content: Text(AppLocalizations.of(context)!.mealCreated)),
            );
      } else {
        await repo.updateMeal(
          tripId: widget.tripId,
          mealId: widget.mealId!,
          name: _nameController.text,
          mealDateKey: _mealDateKey,
          mealDayPart: mealDayPart,
          participantIds: participantIds,
          chefParticipantId: _chefParticipantId,
          notes: '',
          components: _components,
        );
        if (!mounted) return;
        setState(_saveCurrentAsBaseline);
        ScaffoldMessenger.of(context)
            .showSnackBar(
              SnackBar(content: Text(AppLocalizations.of(context)!.mealUpdated)),
            );
      }
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context)
          .showSnackBar(
            SnackBar(
              content: Text(
                AppLocalizations.of(context)!.commonErrorWithDetails(
                  e.toString(),
                ),
              ),
            ),
          );
    } finally {
      if (mounted) setState(() => _isSaving = false);
    }
  }

  Future<void> _confirmAndDelete() async {
    if (widget.isCreate || _isDeleting) return;
    final confirm = await showDialog<bool>(
      context: context,
      builder: (dialogContext) => AlertDialog(
        title: Text(AppLocalizations.of(context)!.mealDeleteTitle),
        content: Text(AppLocalizations.of(context)!.mealDeleteBody),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(dialogContext).pop(false),
            child: Text(AppLocalizations.of(context)!.commonCancel),
          ),
          FilledButton(
            onPressed: () => Navigator.of(dialogContext).pop(true),
            child: Text(AppLocalizations.of(context)!.commonDelete),
          ),
        ],
      ),
    );
    if (confirm != true || !mounted) return;

    setState(() => _isDeleting = true);
    try {
      await ref.read(mealsRepositoryProvider).deleteMeal(
            tripId: widget.tripId,
            mealId: widget.mealId!,
          );
      if (!mounted) return;
      Navigator.of(context).pop();
      ScaffoldMessenger.of(context)
          .showSnackBar(
            SnackBar(content: Text(AppLocalizations.of(context)!.mealDeleted)),
          );
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context)
          .showSnackBar(
            SnackBar(
              content: Text(
                AppLocalizations.of(context)!.commonErrorWithDetails(
                  e.toString(),
                ),
              ),
            ),
          );
    } finally {
      if (mounted) setState(() => _isDeleting = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context)!;
    final tripAsync = ref.watch(tripStreamProvider(widget.tripId));
    final catalogAsync = ref.watch(ingredientCatalogProvider);
    final mealAsync = widget.isCreate
        ? const AsyncValue<TripMeal?>.data(null)
        : ref.watch(
            tripMealStreamProvider(
              (tripId: widget.tripId, mealId: widget.mealId!),
            ),
          );

    return tripAsync.when(
      loading: () =>
          const Scaffold(body: Center(child: CircularProgressIndicator())),
      error: (e, _) => Scaffold(
        appBar: AppBar(),
        body: Center(child: Text(l10n.commonErrorWithDetails(e.toString()))),
      ),
      data: (trip) {
        if (trip == null) {
          return Scaffold(
            appBar: AppBar(),
            body: Center(child: Text(l10n.tripNotFound)),
          );
        }
        final memberIds = trip.memberIds
            .map((id) => id.trim())
            .where((id) => id.isNotEmpty)
            .toList();
        final myUid = FirebaseAuth.instance.currentUser?.uid.trim();
        final labels = <String, String>{
          for (final id in memberIds)
            id: (id == myUid)
                ? l10n.commonMe
                : ((trip.memberPublicLabels[id]?.trim().isNotEmpty ?? false)
                    ? trip.memberPublicLabels[id]!.trim()
                    : l10n.roleParticipant)
        };

        return mealAsync.when(
          loading: () =>
              const Scaffold(body: Center(child: CircularProgressIndicator())),
          error: (e, _) => Scaffold(
            appBar: AppBar(),
            body: Center(child: Text(l10n.commonErrorWithDetails(e.toString()))),
          ),
          data: (meal) {
            if (!widget.isCreate && meal == null) {
              return Scaffold(
                appBar: AppBar(),
                body: Center(child: Text(l10n.mealNotFound)),
              );
            }
            if (meal != null) {
              _hydrateFromMeal(meal);
            } else if (!_isHydrated) {
              _isHydrated = true;
              final tripStart = trip.startDate;
              if (tripStart != null) {
                _mealDate = DateUtils.dateOnly(tripStart);
              }
              _refreshAutoNameIfNeeded();
              _saveCurrentAsBaseline();
            }

            final changedComponentIds = _changedComponentIds;
            final participantIdsForRisk = _participantIds.toList()..sort();
            final participantIdsRiskKey = participantIdsForRisk.join('|');
            final usersAsync = ref.watch(
              usersDataByIdsProvider(participantIdsRiskKey),
            );

            return PopScope(
                canPop: _allowNextPop || !_hasUnsavedChanges,
                onPopInvokedWithResult: (didPop, _) async {
                  if (didPop) return;
                  final allow = await _confirmDiscardIfNeeded();
                  if (!allow || !context.mounted) return;
                  setState(() => _allowNextPop = true);
                  Navigator.of(context).pop();
                },
                child: Scaffold(
                  appBar: AppBar(
                    title: Text(
                      '${widget.isCreate ? l10n.mealNew : l10n.mealEdit}'
                      '${_hasUnsavedChanges ? ' • ${l10n.commonUnsaved}' : ''}',
                    ),
                    actions: [
                      if (!widget.isCreate)
                        IconButton(
                          tooltip: l10n.commonDelete,
                          onPressed: _isDeleting ? null : _confirmAndDelete,
                          icon: _isDeleting
                              ? const SizedBox(
                                  width: 20,
                                  height: 20,
                                  child:
                                      CircularProgressIndicator(strokeWidth: 2),
                                )
                              : const Icon(Icons.delete_outline),
                        ),
                    ],
                  ),
                  body: Form(
                    key: _formKey,
                    child: ListView(
                      padding: const EdgeInsets.all(16),
                      children: [
                        TextFormField(
                          controller: _nameController,
                          textInputAction: TextInputAction.done,
                          decoration: InputDecoration(
                            labelText: l10n.mealNameLabel,
                            border: OutlineInputBorder(),
                          ),
                          validator: (value) {
                            if ((value ?? '').trim().isEmpty) {
                              return l10n.mealNameRequired;
                            }
                            return null;
                          },
                        ),
                        const SizedBox(height: 12),
                        ListTile(
                          contentPadding: EdgeInsets.zero,
                          title: Text(l10n.commonDate),
                          subtitle: Text(
                            DateFormat(
                              'EEEE d MMMM yyyy',
                              Localizations.localeOf(context).toString(),
                            ).format(_mealDate),
                          ),
                          trailing: TextButton.icon(
                            onPressed: _pickDate,
                            icon: const Icon(Icons.calendar_today_outlined),
                            label: Text(l10n.commonChoose),
                          ),
                        ),
                        const SizedBox(height: 8),
                        Text(
                          l10n.mealMomentLabel,
                          style: Theme.of(context).textTheme.labelLarge,
                        ),
                        const SizedBox(height: 8),
                        Wrap(
                          spacing: 8,
                          children: [
                            for (final part in TripDayPart.values)
                              ChoiceChip(
                                label: Text(_dayPartLabel(context, part)),
                                selected: _mealDayPart == part,
                                onSelected: (_) => setState(() {
                                  _mealDayPart = part;
                                  _refreshAutoNameIfNeeded();
                                }),
                              ),
                          ],
                        ),
                        const SizedBox(height: 16),
                        Row(
                          children: [
                            Expanded(
                              child: Text(
                                l10n.mealParticipantsCount(_participantIds.length),
                                style: Theme.of(context).textTheme.labelLarge,
                              ),
                            ),
                            TextButton.icon(
                              onPressed: () =>
                                  _autoRecalculateParticipants(memberIds),
                              icon: const Icon(Icons.auto_fix_high_outlined),
                              label: Text(l10n.commonAuto),
                            ),
                            TextButton.icon(
                              onPressed: () => _selectAllParticipants(memberIds),
                              icon: const Icon(Icons.done_all_outlined),
                              label: Text(l10n.commonSelectAll),
                            ),
                          ],
                        ),
                        const SizedBox(height: 8),
                        Text(
                          l10n.mealChefLongPressHint,
                          style: Theme.of(context).textTheme.bodySmall?.copyWith(
                                color: Theme.of(context).colorScheme.onSurfaceVariant,
                              ),
                        ),
                        const SizedBox(height: 8),
                        Wrap(
                          spacing: 8,
                          runSpacing: 8,
                          children: [
                            for (final memberId in memberIds)
                              GestureDetector(
                                onLongPress: () => _toggleChefParticipant(memberId),
                                child: Builder(
                                  builder: (context) {
                                    final isSelected =
                                        _participantIds.contains(memberId);
                                    final isChef = _chefParticipantId == memberId;
                                    return FilterChip(
                                      showCheckmark: !isChef,
                                      label: Row(
                                        mainAxisSize: MainAxisSize.min,
                                        children: [
                                          if (isChef) ...[
                                            SvgPicture.asset(
                                              'assets/images/chef_hat.svg',
                                              width: 16,
                                              height: 16,
                                            ),
                                            const SizedBox(width: 6),
                                          ],
                                          Text(
                                            labels[memberId] ??
                                                l10n.roleParticipant,
                                          ),
                                        ],
                                      ),
                                      labelStyle: isChef
                                          ? const TextStyle(
                                              fontWeight: FontWeight.w700,
                                            )
                                          : null,
                                      selected: isSelected,
                                      selectedColor: isChef
                                          ? Theme.of(context)
                                              .colorScheme
                                              .primaryContainer
                                          : null,
                                      side: isChef
                                          ? BorderSide(
                                              color: Theme.of(
                                                context,
                                              ).colorScheme.primary,
                                            )
                                          : null,
                                      onSelected: (selected) {
                                        setState(() {
                                          if (selected) {
                                            _participantIds.add(memberId);
                                          } else {
                                            _participantIds.remove(memberId);
                                            if (_chefParticipantId == memberId) {
                                              _chefParticipantId = null;
                                            }
                                          }
                                        });
                                      },
                                    );
                                  },
                                ),
                              ),
                          ],
                        ),
                        const SizedBox(height: 20),
                        Row(
                          children: [
                            Expanded(
                              child: Text(
                                l10n.mealComponentsTitle,
                                style: Theme.of(context).textTheme.titleMedium,
                              ),
                            ),
                            PopupMenuButton<MealComponentKind>(
                              tooltip: l10n.mealAddComponent,
                              onSelected: _addComponent,
                              itemBuilder: (context) => [
                                for (final kind in MealComponentKind.values)
                                  PopupMenuItem(
                                    value: kind,
                                    child: Text(
                                      l10n.mealAddComponentWithKind(
                                        _componentKindLabel(l10n, kind),
                                      ),
                                    ),
                                  ),
                              ],
                              child: const Padding(
                                padding: EdgeInsets.symmetric(horizontal: 8),
                                child: Icon(Icons.add_circle_outline),
                              ),
                            ),
                          ],
                        ),
                        const SizedBox(height: 8),
                        if (_components.isEmpty)
                          Text(
                            l10n.mealAddComponentHint,
                            style: Theme.of(context).textTheme.bodyMedium,
                          )
                        else
                          ReorderableListView.builder(
                            shrinkWrap: true,
                            physics: const NeverScrollableScrollPhysics(),
                            buildDefaultDragHandles: false,
                            itemCount: _components.length,
                            onReorder: _reorderComponents,
                            itemBuilder: (context, index) {
                              final component = _components[index];
                              final usersData = usersAsync.asData?.value;
                              final catalogItems = catalogAsync.asData?.value;
                              final participantAllergenIds = usersData == null
                                  ? <String>{}
                                  : participantAllergenIdsFromUsersData(
                                      usersData,
                                      _participantIds,
                                    );
                              final risk = catalogItems == null
                                  ? null
                                  : buildMealComponentRisks(
                                      components: [component],
                                      catalogItems: catalogItems,
                                      participantAllergenIds:
                                          participantAllergenIds,
                                    )[component.id];
                              final allergenLabelById = <String, String>{
                                if (catalogItems != null)
                                  for (final item in catalogItems
                                      .where((it) => it.type == 'allergen'))
                                    item.id: item.label,
                              };

                              return Card(
                                key: ValueKey(component.id),
                                margin: const EdgeInsets.only(bottom: 12),
                                child: ListTile(
                                  onTap: catalogItems == null
                                      ? null
                                      : () => _openComponentEditor(
                                            component: component,
                                            catalogItems: catalogItems,
                                            participantAllergenIds:
                                                participantAllergenIds,
                                          ),
                                  leading: ReorderableDragStartListener(
                                    index: index,
                                    child: const Padding(
                                      padding:
                                          EdgeInsets.symmetric(horizontal: 4),
                                      child: Icon(Icons.drag_indicator),
                                    ),
                                  ),
                                  title: Text(
                                    component.title.trim().isEmpty
                                        ? _componentKindLabel(l10n, component.kind)
                                        : component.title.trim(),
                                  ),
                                  subtitle: Text(
                                    l10n.mealIngredientsCount(
                                      component.ingredients.length,
                                    ),
                                  ),
                                  trailing: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    children: [
                                      if (changedComponentIds
                                          .contains(component.id))
                                        Tooltip(
                                          message: l10n.mealComponentChangedUnsaved,
                                          child:
                                              Icon(Icons.edit_note, size: 20),
                                        ),
                                      if (risk != null &&
                                          (risk.containsAllergenIds
                                                  .isNotEmpty ||
                                              risk.mayContainAllergenIds
                                                  .isNotEmpty))
                                        Tooltip(
                                          message: [
                                            ...risk.containsAllergenIds.map((id) =>
                                                l10n.mealContainsAllergen(
                                                  allergenLabelById[id] ?? id,
                                                )),
                                            ...risk.mayContainAllergenIds.map(
                                                (id) =>
                                                    l10n.mealMayContainAllergen(
                                                      allergenLabelById[id] ?? id,
                                                    )),
                                          ].join('\n'),
                                          child: const Icon(
                                            Icons.warning_amber_rounded,
                                            color: Colors.orange,
                                          ),
                                        ),
                                      IconButton(
                                        tooltip: l10n.mealDeleteComponent,
                                        onPressed: () =>
                                            _deleteComponent(component.id),
                                        icon: const Icon(Icons.delete_outline),
                                      ),
                                      const Icon(Icons.chevron_right),
                                    ],
                                  ),
                                ),
                              );
                            },
                          ),
                      ],
                    ),
                  ),
                  bottomNavigationBar: SafeArea(
                    top: false,
                    child: Padding(
                      padding: const EdgeInsets.fromLTRB(16, 8, 16, 16),
                      child: FilledButton.icon(
                        onPressed: _isSaving ? null : _save,
                        icon: _isSaving
                            ? const SizedBox(
                                width: 16,
                                height: 16,
                                child:
                                    CircularProgressIndicator(strokeWidth: 2),
                              )
                            : const Icon(Icons.save_outlined),
                        label: Text(
                          _isSaving ? l10n.commonSaving : l10n.commonSave,
                        ),
                      ),
                    ),
                  ),
                ));
          },
        );
      },
    );
  }
}

String _dayPartLabel(BuildContext context, TripDayPart dayPart) {
  final l10n = AppLocalizations.of(context)!;
  return switch (dayPart) {
    TripDayPart.morning => l10n.dayPartMorning,
    TripDayPart.midday => l10n.dayPartMidday,
    TripDayPart.evening => l10n.dayPartEvening,
  };
}
