import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import 'package:planerz/features/ingredients/data/ingredient_catalog_item.dart';
import 'package:planerz/features/ingredients/data/ingredient_catalog_repository.dart';
import 'package:planerz/features/meals/data/meal_component_risks.dart';
import 'package:planerz/features/meals/data/meals_repository.dart';
import 'package:planerz/features/meals/data/trip_meal.dart';
import 'package:planerz/features/meals/presentation/meal_component_editor_page.dart';
import 'package:planerz/features/trips/data/trip_day_part.dart';
import 'package:planerz/features/trips/data/trip_member_stay.dart';
import 'package:planerz/features/trips/data/trips_repository.dart';

class TripMealDetailsPage extends ConsumerStatefulWidget {
  const TripMealDetailsPage({
    super.key,
    required this.tripId,
    this.mealId,
  });

  final String tripId;
  final String? mealId;

  bool get isCreate => mealId == null || mealId!.trim().isEmpty;

  @override
  ConsumerState<TripMealDetailsPage> createState() =>
      _TripMealDetailsPageState();
}

class _TripMealDetailsPageState extends ConsumerState<TripMealDetailsPage> {
  final _formKey = GlobalKey<FormState>();
  late final TextEditingController _nameController;
  bool _isSaving = false;
  bool _isDeleting = false;
  bool _isHydrated = false;
  DateTime _mealDate = DateUtils.dateOnly(DateTime.now());
  TripDayPart _mealDayPart = TripDayPart.midday;
  Set<String> _participantIds = <String>{};
  String _lastAutoGeneratedName = '';
  List<MealComponent> _components = const [];
  String? _initialMealSignature;
  Map<String, String> _initialComponentSignatures = const {};
  bool _allowNextPop = false;

  @override
  void initState() {
    super.initState();
    _nameController = TextEditingController();
  }

  @override
  void dispose() {
    _nameController.dispose();
    super.dispose();
  }

  String get _mealDateKey => TripMemberStay.dateKeyFromDateTime(_mealDate);

  String _defaultMealName() {
    final moment = switch (_mealDayPart) {
      TripDayPart.morning => 'Petit dej',
      TripDayPart.midday => 'Dejeuner',
      TripDayPart.evening => 'Diner',
    };
    final dayName = DateFormat('EEEE', 'fr_FR').format(_mealDate);
    final dateLabel = DateFormat('d MMMM', 'fr_FR').format(_mealDate);
    return '$moment $dayName $dateLabel';
  }

  void _refreshAutoNameIfNeeded() {
    if (!widget.isCreate) return;
    final current = _nameController.text.trim();
    final nextAutoName = _defaultMealName();
    final canReplace = current.isEmpty || current == _lastAutoGeneratedName;
    if (!canReplace) return;
    _nameController.text = nextAutoName;
    _lastAutoGeneratedName = nextAutoName;
  }

  void _hydrateFromMeal(TripMeal meal) {
    if (_isHydrated) return;
    _nameController.text = meal.name;
    _mealDate = meal.mealDateAsDateTime;
    _mealDayPart = meal.mealDayPart;
    _participantIds = meal.participantIds.toSet();
    _components = meal.components.toList(growable: true)
      ..sort((a, b) => a.order.compareTo(b.order));
    _saveCurrentAsBaseline();
    _isHydrated = true;
  }

  String _componentSignature(MealComponent component) {
    final ingredients = component.ingredients
        .map(
          (ingredient) =>
              '${ingredient.catalogItemId.trim()}|${ingredient.label.trim()}|'
              '${ingredient.quantityValue}|${ingredient.quantityUnit.trim()}',
        )
        .join('~');
    return '${component.order}|${component.kind.firestoreValue}|'
        '${component.title.trim()}|$ingredients';
  }

  Map<String, String> _componentSignaturesById(List<MealComponent> components) {
    return {
      for (final component in components)
        component.id: _componentSignature(component),
    };
  }

  String _currentMealSignature() {
    final sortedParticipants = _participantIds.toList()..sort();
    final componentsSignature = _components
        .map((component) => '${component.id}:${_componentSignature(component)}')
        .join('||');
    return '${_nameController.text.trim()}|$_mealDateKey|'
        '${tripDayPartToFirestore(_mealDayPart)}|'
        '${sortedParticipants.join(",")}|$componentsSignature';
  }

  void _saveCurrentAsBaseline() {
    _initialMealSignature = _currentMealSignature();
    _initialComponentSignatures = _componentSignaturesById(_components);
  }

  bool get _hasUnsavedChanges {
    final baseline = _initialMealSignature;
    if (baseline == null) return false;
    return baseline != _currentMealSignature();
  }

  Set<String> get _changedComponentIds {
    final current = _componentSignaturesById(_components);
    final changed = <String>{};
    for (final entry in current.entries) {
      if (_initialComponentSignatures[entry.key] != entry.value) {
        changed.add(entry.key);
      }
    }
    for (final initialId in _initialComponentSignatures.keys) {
      if (!current.containsKey(initialId)) {
        changed.add(initialId);
      }
    }
    return changed;
  }

  Future<bool> _confirmDiscardIfNeeded() async {
    if (!_hasUnsavedChanges) return true;
    final confirm = await showDialog<bool>(
      context: context,
      builder: (dialogContext) => AlertDialog(
        title: const Text('Modifications non enregistrées'),
        content: const Text(
          'Tu as des changements non enregistrés. Quitter sans enregistrer ?',
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(dialogContext).pop(false),
            child: const Text('Rester'),
          ),
          FilledButton(
            onPressed: () => Navigator.of(dialogContext).pop(true),
            child: const Text('Quitter'),
          ),
        ],
      ),
    );
    return confirm == true;
  }

  void _addComponent(MealComponentKind kind) {
    setState(() {
      _components = [
        ..._components,
        MealComponent(
          id: 'cmp_${DateTime.now().microsecondsSinceEpoch}_${_components.length}',
          kind: kind,
          order: _components.length,
          ingredients: const [],
        ),
      ];
    });
  }

  Future<void> _openComponentEditor({
    required MealComponent component,
    required List<IngredientCatalogItem> catalogItems,
    required Set<String> participantAllergenIds,
  }) async {
    final updated = await Navigator.of(context).push<MealComponent>(
      MaterialPageRoute(
        builder: (_) => MealComponentEditorPage(
          component: component,
          catalogItems: catalogItems,
          participantAllergenIds: participantAllergenIds,
        ),
      ),
    );
    if (!mounted || updated == null) return;
    _updateComponent(updated.copyWith(order: component.order));
  }

  void _updateComponent(MealComponent next) {
    setState(() {
      _components = _components
          .map((component) => component.id == next.id ? next : component)
          .toList(growable: false);
    });
  }

  void _deleteComponent(String componentId) {
    setState(() {
      final filtered = _components
          .where((component) => component.id != componentId)
          .toList(growable: false);
      _components = [
        for (var i = 0; i < filtered.length; i++)
          filtered[i].copyWith(order: i),
      ];
    });
  }

  void _reorderComponents(int oldIndex, int newIndex) {
    setState(() {
      final next = _components.toList(growable: true);
      if (newIndex > oldIndex) {
        newIndex -= 1;
      }
      final moved = next.removeAt(oldIndex);
      next.insert(newIndex, moved);
      _components = [
        for (var i = 0; i < next.length; i++) next[i].copyWith(order: i),
      ];
    });
  }

  Future<void> _autoRecalculateParticipants(List<String> memberIds) async {
    try {
      final ids =
          await ref.read(mealsRepositoryProvider).calculateMealParticipants(
                tripId: widget.tripId,
                mealDateKey: _mealDateKey,
                mealDayPart: tripDayPartToFirestore(_mealDayPart),
                allMemberIds: memberIds,
              );
      if (!mounted) return;
      setState(() => _participantIds = ids.toSet());
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context)
          .showSnackBar(SnackBar(content: Text('Erreur: $e')));
    }
  }

  Future<void> _pickDate() async {
    final picked = await showDatePicker(
      context: context,
      locale: const Locale('fr', 'FR'),
      initialDate: _mealDate,
      firstDate: DateTime(2000),
      lastDate: DateTime(2100),
      helpText: 'Date du repas',
    );
    if (picked == null || !mounted) return;
    setState(() {
      _mealDate = DateUtils.dateOnly(picked);
      _refreshAutoNameIfNeeded();
    });
  }

  Future<void> _save() async {
    if (_isSaving) return;
    final form = _formKey.currentState;
    if (form == null || !form.validate()) return;

    setState(() => _isSaving = true);
    try {
      final repo = ref.read(mealsRepositoryProvider);
      final mealDayPart = tripDayPartToFirestore(_mealDayPart);
      final participantIds = _participantIds.toList()..sort();
      if (widget.isCreate) {
        await repo.addMeal(
          tripId: widget.tripId,
          name: _nameController.text,
          mealDateKey: _mealDateKey,
          mealDayPart: mealDayPart,
          participantIds: participantIds,
          notes: '',
          components: _components,
        );
        if (!mounted) return;
        Navigator.of(context).pop();
        ScaffoldMessenger.of(context)
            .showSnackBar(const SnackBar(content: Text('Repas créé')));
      } else {
        await repo.updateMeal(
          tripId: widget.tripId,
          mealId: widget.mealId!,
          name: _nameController.text,
          mealDateKey: _mealDateKey,
          mealDayPart: mealDayPart,
          participantIds: participantIds,
          notes: '',
          components: _components,
        );
        if (!mounted) return;
        setState(_saveCurrentAsBaseline);
        ScaffoldMessenger.of(context)
            .showSnackBar(const SnackBar(content: Text('Repas mis à jour')));
      }
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context)
          .showSnackBar(SnackBar(content: Text('Erreur: $e')));
    } finally {
      if (mounted) setState(() => _isSaving = false);
    }
  }

  Future<void> _confirmAndDelete() async {
    if (widget.isCreate || _isDeleting) return;
    final confirm = await showDialog<bool>(
      context: context,
      builder: (dialogContext) => AlertDialog(
        title: const Text('Supprimer ce repas ?'),
        content: const Text('Ce repas sera supprimé définitivement.'),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(dialogContext).pop(false),
            child: const Text('Annuler'),
          ),
          FilledButton(
            onPressed: () => Navigator.of(dialogContext).pop(true),
            child: const Text('Supprimer'),
          ),
        ],
      ),
    );
    if (confirm != true || !mounted) return;

    setState(() => _isDeleting = true);
    try {
      await ref.read(mealsRepositoryProvider).deleteMeal(
            tripId: widget.tripId,
            mealId: widget.mealId!,
          );
      if (!mounted) return;
      Navigator.of(context).pop();
      ScaffoldMessenger.of(context)
          .showSnackBar(const SnackBar(content: Text('Repas supprimé')));
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context)
          .showSnackBar(SnackBar(content: Text('Erreur: $e')));
    } finally {
      if (mounted) setState(() => _isDeleting = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final tripAsync = ref.watch(tripStreamProvider(widget.tripId));
    final participantIdsForRisk = _participantIds.toList()..sort();
    final participantIdsRiskKey = participantIdsForRisk.join('|');
    final usersAsync = ref.watch(usersDataByIdsProvider(participantIdsRiskKey));
    final catalogAsync = ref.watch(ingredientCatalogProvider);
    final mealAsync = widget.isCreate
        ? const AsyncValue<TripMeal?>.data(null)
        : ref.watch(
            tripMealStreamProvider(
              (tripId: widget.tripId, mealId: widget.mealId!),
            ),
          );

    return tripAsync.when(
      loading: () =>
          const Scaffold(body: Center(child: CircularProgressIndicator())),
      error: (e, _) => Scaffold(
        appBar: AppBar(),
        body: Center(child: Text('Erreur: $e')),
      ),
      data: (trip) {
        if (trip == null) {
          return Scaffold(
            appBar: AppBar(),
            body: const Center(child: Text('Voyage introuvable')),
          );
        }
        final memberIds = trip.memberIds
            .map((id) => id.trim())
            .where((id) => id.isNotEmpty)
            .toList();
        final myUid = FirebaseAuth.instance.currentUser?.uid.trim();
        final labels = <String, String>{
          for (final id in memberIds)
            id: (id == myUid)
                ? 'Moi'
                : ((trip.memberPublicLabels[id]?.trim().isNotEmpty ?? false)
                    ? trip.memberPublicLabels[id]!.trim()
                    : 'Participant')
        };

        return mealAsync.when(
          loading: () =>
              const Scaffold(body: Center(child: CircularProgressIndicator())),
          error: (e, _) => Scaffold(
            appBar: AppBar(),
            body: Center(child: Text('Erreur: $e')),
          ),
          data: (meal) {
            if (!widget.isCreate && meal == null) {
              return Scaffold(
                appBar: AppBar(),
                body: const Center(child: Text('Repas introuvable')),
              );
            }
            if (meal != null) {
              _hydrateFromMeal(meal);
            } else if (!_isHydrated) {
              _isHydrated = true;
              final tripStart = trip.startDate;
              if (tripStart != null) {
                _mealDate = DateUtils.dateOnly(tripStart);
              }
              _refreshAutoNameIfNeeded();
              _saveCurrentAsBaseline();
            }

            final changedComponentIds = _changedComponentIds;

            return PopScope(
                canPop: _allowNextPop || !_hasUnsavedChanges,
                onPopInvokedWithResult: (didPop, _) async {
                  if (didPop) return;
                  final allow = await _confirmDiscardIfNeeded();
                  if (!allow || !mounted) return;
                  setState(() => _allowNextPop = true);
                  Navigator.of(context).pop();
                },
                child: Scaffold(
                  appBar: AppBar(
                    title: Text(
                      '${widget.isCreate ? 'Nouveau repas' : 'Modifier le repas'}'
                      '${_hasUnsavedChanges ? ' • non enregistré' : ''}',
                    ),
                    actions: [
                      if (!widget.isCreate)
                        IconButton(
                          tooltip: 'Supprimer',
                          onPressed: _isDeleting ? null : _confirmAndDelete,
                          icon: _isDeleting
                              ? const SizedBox(
                                  width: 20,
                                  height: 20,
                                  child:
                                      CircularProgressIndicator(strokeWidth: 2),
                                )
                              : const Icon(Icons.delete_outline),
                        ),
                    ],
                  ),
                  body: Form(
                    key: _formKey,
                    child: ListView(
                      padding: const EdgeInsets.all(16),
                      children: [
                        TextFormField(
                          controller: _nameController,
                          textInputAction: TextInputAction.done,
                          decoration: const InputDecoration(
                            labelText: 'Nom du repas',
                            border: OutlineInputBorder(),
                          ),
                          validator: (value) {
                            if ((value ?? '').trim().isEmpty) {
                              return 'Nom obligatoire';
                            }
                            return null;
                          },
                        ),
                        const SizedBox(height: 12),
                        ListTile(
                          contentPadding: EdgeInsets.zero,
                          title: const Text('Date'),
                          subtitle: Text(DateFormat('EEEE d MMMM yyyy', 'fr_FR')
                              .format(_mealDate)),
                          trailing: TextButton.icon(
                            onPressed: _pickDate,
                            icon: const Icon(Icons.calendar_today_outlined),
                            label: const Text('Choisir'),
                          ),
                        ),
                        const SizedBox(height: 8),
                        Text(
                          'Moment',
                          style: Theme.of(context).textTheme.labelLarge,
                        ),
                        const SizedBox(height: 8),
                        Wrap(
                          spacing: 8,
                          children: [
                            for (final part in TripDayPart.values)
                              ChoiceChip(
                                label: Text(tripDayPartLabelFr(part)),
                                selected: _mealDayPart == part,
                                onSelected: (_) => setState(() {
                                  _mealDayPart = part;
                                  _refreshAutoNameIfNeeded();
                                }),
                              ),
                          ],
                        ),
                        const SizedBox(height: 16),
                        Row(
                          children: [
                            Expanded(
                              child: Text(
                                'Participants (${_participantIds.length})',
                                style: Theme.of(context).textTheme.labelLarge,
                              ),
                            ),
                            TextButton.icon(
                              onPressed: () =>
                                  _autoRecalculateParticipants(memberIds),
                              icon: const Icon(Icons.auto_fix_high_outlined),
                              label: const Text('Auto'),
                            ),
                          ],
                        ),
                        const SizedBox(height: 8),
                        Wrap(
                          spacing: 8,
                          runSpacing: 8,
                          children: [
                            for (final memberId in memberIds)
                              FilterChip(
                                label: Text(labels[memberId] ?? 'Participant'),
                                selected: _participantIds.contains(memberId),
                                onSelected: (selected) {
                                  setState(() {
                                    if (selected) {
                                      _participantIds.add(memberId);
                                    } else {
                                      _participantIds.remove(memberId);
                                    }
                                  });
                                },
                              ),
                          ],
                        ),
                        const SizedBox(height: 20),
                        Row(
                          children: [
                            Expanded(
                              child: Text(
                                'Composants du repas',
                                style: Theme.of(context).textTheme.titleMedium,
                              ),
                            ),
                            PopupMenuButton<MealComponentKind>(
                              tooltip: 'Ajouter un composant',
                              onSelected: _addComponent,
                              itemBuilder: (context) => [
                                for (final kind in MealComponentKind.values)
                                  PopupMenuItem(
                                    value: kind,
                                    child: Text('Ajouter ${kind.labelFr}'),
                                  ),
                              ],
                              child: const Padding(
                                padding: EdgeInsets.symmetric(horizontal: 8),
                                child: Icon(Icons.add_circle_outline),
                              ),
                            ),
                          ],
                        ),
                        const SizedBox(height: 8),
                        if (_components.isEmpty)
                          Text(
                            'Ajoute un composant (entree, plat, dessert, autre).',
                            style: Theme.of(context).textTheme.bodyMedium,
                          )
                        else
                          ReorderableListView.builder(
                            shrinkWrap: true,
                            physics: const NeverScrollableScrollPhysics(),
                            buildDefaultDragHandles: false,
                            itemCount: _components.length,
                            onReorder: _reorderComponents,
                            itemBuilder: (context, index) {
                              final component = _components[index];
                              final usersData = usersAsync.asData?.value;
                              final catalogItems = catalogAsync.asData?.value;
                              final participantAllergenIds = usersData == null
                                  ? <String>{}
                                  : participantAllergenIdsFromUsersData(
                                      usersData,
                                      _participantIds,
                                    );
                              final risk = catalogItems == null
                                  ? null
                                  : buildMealComponentRisks(
                                      components: [component],
                                      catalogItems: catalogItems,
                                      participantAllergenIds:
                                          participantAllergenIds,
                                    )[component.id];
                              final allergenLabelById = <String, String>{
                                if (catalogItems != null)
                                  for (final item in catalogItems
                                      .where((it) => it.type == 'allergen'))
                                    item.id: item.label,
                              };

                              return Card(
                                key: ValueKey(component.id),
                                margin: const EdgeInsets.only(bottom: 12),
                                child: ListTile(
                                  onTap: catalogItems == null
                                      ? null
                                      : () => _openComponentEditor(
                                            component: component,
                                            catalogItems: catalogItems,
                                            participantAllergenIds:
                                                participantAllergenIds,
                                          ),
                                  leading: ReorderableDragStartListener(
                                    index: index,
                                    child: const Padding(
                                      padding:
                                          EdgeInsets.symmetric(horizontal: 4),
                                      child: Icon(Icons.drag_indicator),
                                    ),
                                  ),
                                  title: Text(
                                    component.title.trim().isEmpty
                                        ? component.kind.labelFr
                                        : component.title.trim(),
                                  ),
                                  subtitle: Text(
                                    '${component.ingredients.length} ingrédient(s)',
                                  ),
                                  trailing: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    children: [
                                      if (changedComponentIds
                                          .contains(component.id))
                                        const Tooltip(
                                          message:
                                              'Composant modifié non enregistré',
                                          child:
                                              Icon(Icons.edit_note, size: 20),
                                        ),
                                      if (risk != null &&
                                          (risk.containsAllergenIds
                                                  .isNotEmpty ||
                                              risk.mayContainAllergenIds
                                                  .isNotEmpty))
                                        Tooltip(
                                          message: [
                                            ...risk.containsAllergenIds.map((id) =>
                                                'Contient ${allergenLabelById[id] ?? id}'),
                                            ...risk.mayContainAllergenIds.map(
                                                (id) =>
                                                    'Peut contenir ${allergenLabelById[id] ?? id}'),
                                          ].join('\n'),
                                          child: const Icon(
                                            Icons.warning_amber_rounded,
                                            color: Colors.orange,
                                          ),
                                        ),
                                      IconButton(
                                        tooltip: 'Supprimer ce composant',
                                        onPressed: () =>
                                            _deleteComponent(component.id),
                                        icon: const Icon(Icons.delete_outline),
                                      ),
                                      const Icon(Icons.chevron_right),
                                    ],
                                  ),
                                ),
                              );
                            },
                          ),
                      ],
                    ),
                  ),
                  bottomNavigationBar: SafeArea(
                    top: false,
                    child: Padding(
                      padding: const EdgeInsets.fromLTRB(16, 8, 16, 16),
                      child: FilledButton.icon(
                        onPressed: _isSaving ? null : _save,
                        icon: _isSaving
                            ? const SizedBox(
                                width: 16,
                                height: 16,
                                child:
                                    CircularProgressIndicator(strokeWidth: 2),
                              )
                            : const Icon(Icons.save_outlined),
                        label: Text(
                            _isSaving ? 'Enregistrement...' : 'Enregistrer'),
                      ),
                    ),
                  ),
                ));
          },
        );
      },
    );
  }
}
