// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your production Firebase app.
class DefaultFirebaseOptionsProd {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptionsProd are not configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptionsProd are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6N9_UQcpIiXNAh9VxlwYmYoYgw5L_WqM',
    appId: '1:968267093466:web:c8bb48142b46a05cd29ce3',
    messagingSenderId: '968267093466',
    projectId: 'planerz',
    authDomain: 'planerz.firebaseapp.com',
    storageBucket: 'planerz.firebasestorage.app',
    measurementId: 'G-NGGPNLLR0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAbqV4V0XhqdKQI-MShFzbl3JWuBGrNwo',
    appId: '1:968267093466:android:dedcff179c3fc51fd29ce3',
    messagingSenderId: '968267093466',
    projectId: 'planerz',
    storageBucket: 'planerz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8hf0qUyo_3eWHBbuPN0B8WL8gWYEaEI0',
    appId: '1:968267093466:ios:b4cefce64376cd54d29ce3',
    messagingSenderId: '968267093466',
    projectId: 'planerz',
    storageBucket: 'planerz.firebasestorage.app',
    androidClientId: '968267093466-flhm7osctcqf5g9npfqo0crtnor3s8om.apps.googleusercontent.com',
    iosClientId: '968267093466-db1re1pv2r6ddpskp3khq15sf7o6sg8f.apps.googleusercontent.com',
    iosBundleId: 'fr.centuryspine.planerz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8hf0qUyo_3eWHBbuPN0B8WL8gWYEaEI0',
    appId: '1:968267093466:ios:b4cefce64376cd54d29ce3',
    messagingSenderId: '968267093466',
    projectId: 'planerz',
    storageBucket: 'planerz.firebasestorage.app',
    androidClientId: '968267093466-flhm7osctcqf5g9npfqo0crtnor3s8om.apps.googleusercontent.com',
    iosClientId: '968267093466-db1re1pv2r6ddpskp3khq15sf7o6sg8f.apps.googleusercontent.com',
    iosBundleId: 'fr.centuryspine.planerz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6N9_UQcpIiXNAh9VxlwYmYoYgw5L_WqM',
    appId: '1:968267093466:web:f04bee3c5e841154d29ce3',
    messagingSenderId: '968267093466',
    projectId: 'planerz',
    authDomain: 'planerz.firebaseapp.com',
    storageBucket: 'planerz.firebasestorage.app',
    measurementId: 'G-32WK1Q6N89',
  );

}