// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXFZrpXlQa1_FqNmbTVUsOlTcHDcs3pPU',
    appId: '1:936277491452:web:1794a04a8c81d6f8f1e179',
    messagingSenderId: '936277491452',
    projectId: 'planzers',
    authDomain: 'planzers.firebaseapp.com',
    storageBucket: 'planzers.firebasestorage.app',
    measurementId: 'G-Z68T9LKMH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoTSZLo8BZqy21Aym5nwGMucnylehWnj0',
    appId: '1:936277491452:android:43d7c2d65282a6ebf1e179',
    messagingSenderId: '936277491452',
    projectId: 'planzers',
    storageBucket: 'planzers.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6e1d6ejoOofBGHmrk2Ts8Gkurfwj65Yg',
    appId: '1:936277491452:ios:256ff6995b4d0ceef1e179',
    messagingSenderId: '936277491452',
    projectId: 'planzers',
    storageBucket: 'planzers.firebasestorage.app',
    iosClientId: '936277491452-34g7ggce0othki802d4sn4v5vkgmnn54.apps.googleusercontent.com',
    iosBundleId: 'com.planzers.planzers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6e1d6ejoOofBGHmrk2Ts8Gkurfwj65Yg',
    appId: '1:936277491452:ios:256ff6995b4d0ceef1e179',
    messagingSenderId: '936277491452',
    projectId: 'planzers',
    storageBucket: 'planzers.firebasestorage.app',
    iosClientId: '936277491452-34g7ggce0othki802d4sn4v5vkgmnn54.apps.googleusercontent.com',
    iosBundleId: 'com.planzers.planzers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXFZrpXlQa1_FqNmbTVUsOlTcHDcs3pPU',
    appId: '1:936277491452:web:7682cb5708ece121f1e179',
    messagingSenderId: '936277491452',
    projectId: 'planzers',
    authDomain: 'planzers.firebaseapp.com',
    storageBucket: 'planzers.firebasestorage.app',
    measurementId: 'G-PR5BTR8MWV',
  );

}