// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your preview Firebase app.
///
/// Replace this file by running:
/// flutterfire configure --project=planerz-preview --out=lib/firebase_options_preview.dart
class DefaultFirebaseOptionsPreview {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptionsPreview are not configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptionsPreview are not supported for this platform.',
        );
    }
  }

  // Temporary fallback values copied from prod.

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh1WtquB9vido6MZDLAPdAA0TqDCqVYWk',
    appId: '1:1072541832110:web:7cf4d82bc5954997546e3f',
    messagingSenderId: '1072541832110',
    projectId: 'planerz-preview',
    authDomain: 'planerz-preview.firebaseapp.com',
    storageBucket: 'planerz-preview.firebasestorage.app',
    measurementId: 'G-8D0916J6F3',
  );

  // They must be replaced with the real "planerz-preview" app IDs.

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiVLR7hMxvMeoMZHAvFlHNLPPZ4I_WugE',
    appId: '1:1072541832110:android:79d6b35d22656140546e3f',
    messagingSenderId: '1072541832110',
    projectId: 'planerz-preview',
    storageBucket: 'planerz-preview.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLAkK3TC-7v802i5jDcU1t4D6HPqXS0BM',
    appId: '1:1072541832110:ios:1d125a79f4c795f6546e3f',
    messagingSenderId: '1072541832110',
    projectId: 'planerz-preview',
    storageBucket: 'planerz-preview.firebasestorage.app',
    androidClientId: '1072541832110-9j7hmsuvf05n42ojsfnkceh5du3kjpi3.apps.googleusercontent.com',
    iosClientId: '1072541832110-ci06gsrark4u7ao8vqbu703linbsbe3k.apps.googleusercontent.com',
    iosBundleId: 'fr.centuryspine.planerz.preview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLAkK3TC-7v802i5jDcU1t4D6HPqXS0BM',
    appId: '1:1072541832110:ios:e23cede5f4af90e5546e3f',
    messagingSenderId: '1072541832110',
    projectId: 'planerz-preview',
    storageBucket: 'planerz-preview.firebasestorage.app',
    androidClientId: '1072541832110-9j7hmsuvf05n42ojsfnkceh5du3kjpi3.apps.googleusercontent.com',
    iosClientId: '1072541832110-3q788tm780et5jp1h9nm4hhpc54p2mu1.apps.googleusercontent.com',
    iosBundleId: 'fr.centuryspine.planerz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh1WtquB9vido6MZDLAPdAA0TqDCqVYWk',
    appId: '1:1072541832110:web:4fd946c263907531546e3f',
    messagingSenderId: '1072541832110',
    projectId: 'planerz-preview',
    authDomain: 'planerz-preview.firebaseapp.com',
    storageBucket: 'planerz-preview.firebasestorage.app',
    measurementId: 'G-RFZ4JWHQY1',
  );

}