// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your preview Firebase app.
///
/// Replace this file by running:
/// flutterfire configure --project=Planzers-preview --out=lib/firebase_options_preview.dart
class DefaultFirebaseOptionsPreview {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptionsPreview are not configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptionsPreview are not supported for this platform.',
        );
    }
  }

  // Temporary fallback values copied from prod.

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA84GI-A3YJGUGnT6XPGa8VZ4NSKSJKsXQ',
    appId: '1:426381891835:web:26bade9d1738a1e419785e',
    messagingSenderId: '426381891835',
    projectId: 'planzers-preview',
    authDomain: 'planzers-preview.firebaseapp.com',
    storageBucket: 'planzers-preview.firebasestorage.app',
  );

  // They must be replaced with the real "Planzers-preview" app IDs.

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJX6EcNcuXnr2E8DzFfDXJhBhSgeCURRQ',
    appId: '1:426381891835:android:45a663058ce12d5e19785e',
    messagingSenderId: '426381891835',
    projectId: 'planzers-preview',
    storageBucket: 'planzers-preview.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDec66Zd9tPZga2WaKv5ze9LwiqDm6HKsY',
    appId: '1:426381891835:ios:91679112f908d89919785e',
    messagingSenderId: '426381891835',
    projectId: 'planzers-preview',
    storageBucket: 'planzers-preview.firebasestorage.app',
    iosClientId: '426381891835-ud77v01t8ler9od6i0u6581t3nblr0iv.apps.googleusercontent.com',
    iosBundleId: 'com.planzers.planzers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDec66Zd9tPZga2WaKv5ze9LwiqDm6HKsY',
    appId: '1:426381891835:ios:91679112f908d89919785e',
    messagingSenderId: '426381891835',
    projectId: 'planzers-preview',
    storageBucket: 'planzers-preview.firebasestorage.app',
    iosClientId: '426381891835-ud77v01t8ler9od6i0u6581t3nblr0iv.apps.googleusercontent.com',
    iosBundleId: 'com.planzers.planzers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA84GI-A3YJGUGnT6XPGa8VZ4NSKSJKsXQ',
    appId: '1:426381891835:web:c4949244c666cbdf19785e',
    messagingSenderId: '426381891835',
    projectId: 'planzers-preview',
    authDomain: 'planzers-preview.firebaseapp.com',
    storageBucket: 'planzers-preview.firebasestorage.app',
  );

}